name: domainradar-collector-extractor
include:
  - ./compose.base.yml

services:
  # Kafka Connect without PostgreSQL, for use in the standalone collection scenarios only
  kafka-connect:
    build:
      context: .
      dockerfile: ./dockerfiles/kafka_connect.Dockerfile
    command: ["/bin/bash", "-c", "/opt/kafka/bin/connect-standalone.sh /opt/kafka-connect/config/1*.properties /opt/kafka-connect/config/mongo/*.properties"]
    depends_on:
      initializer:
        condition: service_completed_successfully
      mongo:
        condition: service_started
    secrets:
      - kafka-truststore
      - client1-keystore
    networks:
      kafka-clients:
        ipv4_address: 192.168.100.10
        aliases: [ "kafka-connect" ]
      databases: {}
      outside-world:
        ipv4_address: 192.168.103.10
    ports:
      - "31002:8083"
    volumes:
      - ./connect_properties/:/opt/kafka-connect/config/
      - kafka-connect-offsets:/tmp/kafka-connect

  standalone-input:
    image: domrad/standalone-input
    depends_on:
      kafka1:
        condition: service_started
      mongo:
        condition: service_started
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-clients
      - databases
    volumes:
      - ./client_properties/standalone_input.toml:/app/config.toml
      - ./misc/testing_domains.txt:/app/sample.txt

  # --- Databases --- #

  mongo:
    image: docker.io/mongo:7
    command: --config /etc/mongod.conf
    restart: always
    secrets:
      - mongo_master_password
      - mongo_connect_password
    volumes:
      - mongo-data:/data/db
      - ./db/mongo/init/:/docker-entrypoint-initdb.d/
      - ./db/mongo/mongod.conf.yml:/etc/mongod.conf
    env_file:
      - ./db/mongo/mongo.env
    ports:
      - "31011:27017"
    networks:
      databases:
        ipv4_address: 192.168.101.3
        aliases: [ "mongo" ]
      outside-world:
        ipv4_address: 192.168.103.21

volumes:
  mongo-data: {}
  kafka-connect-offsets: {}

secrets:
  mongo_master_password:
    file: ./db/mongo/master.secret
  mongo_connect_password:
    file: ./db/mongo/connect.secret
