services:
  kafka1:
    image: docker.io/apache/kafka:3.7.0
    hostname: kafka1
    volumes:
      - kafka1-single-log:/var/lib/kafka/data
    secrets:
      - kafka-truststore
      - kafka1-keystore
    networks:
      kafka-client-network:
        ipv4_address: 192.168.100.2
        aliases: [ "kafka1" ]
    ports:
      - "9093:9093"
    env_file:
      - ./envs/kafka1_single.env

  kafka-connect:
    build:
      context: .
      dockerfile: ./dockerfiles/kafka-connect.Dockerfile
    depends_on:
      initializer:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      mongo:
        condition: service_started
    secrets:
      - kafka-truststore
      - client1-keystore
    networks:
      kafka-client-network:
        ipv4_address: 192.168.100.10
        aliases: [ "kafka-connect" ]
      db-network: {}
    ports:
      - "31002:8083"
    volumes:
      - ./connect_properties/:/opt/kafka-connect/config/
      - kafka-connect-offsets:/tmp/kafka-connect

  kafka-ui:
    image: docker.io/provectuslabs/kafka-ui:latest
    depends_on:
      - kafka1
    secrets:
      - kafka-truststore
      - client1-keystore
    networks:
      kafka-client-network:
        ipv4_address: 192.168.100.11
    ports:
      - "31000:8080"
    volumes:
      - ./client_properties/kafka_ui.yml:/etc/kafkaui/dynamic_config.yaml
    env_file:
      - ./envs/kafka_ui.env
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9093

  webui:
    image: domrad/webui
    depends_on:
      - mongo
    networks:
      db-network:
        ipv4_address: 192.168.101.11
    ports:
      - "31003:3784"
    env_file:
      - ./envs/webui.env

  initializer:
    build:
      context: .  # The root of the domainradar repo
      dockerfile: ./dockerfiles/initializer.Dockerfile
    depends_on:
      - kafka1
    secrets:
      - kafka-truststore
      - client1-keystore
    networks:
      - kafka-client-network
    volumes:
      - ./client_properties/initializer.properties:/scripts/client.properties
    environment:
      - BOOTSTRAP=kafka1:9093
      - COMMAND_CONFIG_FILE=/scripts/client.properties
      - EXTRA_SLEEP=0
      - UPDATE_EXISTING_TOPICS=0

  collector-zone:
    image: domrad/zone
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/zone.toml:/app/config.toml
    
  collector-dns:
    image: domrad/dns
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/dns.toml:/app/config.toml

  collector-tls:
    image: domrad/java-standalone
    command: [ "--col-tls", "-id", "${ID_PREFIX-domrad}", "-p", "/app/client.properties", "-s", "kafka1:9093" ]
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - kafka-truststore
      - client2-keystore
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/tls.properties:/app/client.properties

  collector-nerd:
    image: domrad/java-standalone
    command: [ "--col-nerd", "-id", "${ID_PREFIX-domrad}", "-p", "/app/client.properties", "-s", "kafka1:9093" ]
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - kafka-truststore
      - client2-keystore
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/nerd.properties:/app/client.properties

  collector-geoip:
    image: domrad/java-streams
    command: [ "--col-geoip", "-t", "${THREADS:-4}", "-id", "${ID_PREFIX-domrad}-geoip", "-p", "/app/client.properties", "-s", "kafka1:9093" ]
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - kafka-truststore
      - client2-keystore
    networks:
      - kafka-client-network
    volumes:
      - ./client_properties/geoip.properties:/app/client.properties
      - ./geoip_data/:/app/geoip/

  collector-rdap-dn:
    image: domrad/rdap-dn
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/rdap_dn.toml:/app/config.toml
    
  collector-rdap-ip:
    image: domrad/rdap-ip
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/rdap_ip.toml:/app/config.toml

  collector-rtt:
    image: domrad/rtt
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
      - collector-network
    volumes:
      - ./client_properties/rtt.toml:/app/config.toml
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_ADMIN

  merger:
    image: domrad/java-streams
    command: [ "--merger", "-t", "${THREADS:-4}", "-id", "${ID_PREFIX-domrad}-merger", "-p", "/app/client.properties", "-s", "kafka1:9093" ]
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - kafka-truststore
      - client2-keystore
    networks:
      - kafka-client-network
    volumes:
      - ./client_properties/mergers.properties:/app/client.properties

  extractor:
    image: domrad/extractor
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
    volumes:
      - ./client_properties/extractor.toml:/app/config.toml
      - ./extractor_data/:/app/data/

  classifier-unit:
    image: domrad/classifier
    depends_on:
      initializer:
        condition: service_completed_successfully
    secrets:
      - ca-cert
      - client2-cert
      - client2-key
    networks:
      - kafka-client-network
    volumes:
      - ./client_properties/classifier_unit.toml:/app/config.toml
      - ./clf_models/:/run/models/

  # --- Databases ---

  postgres:
    image: docker.io/postgres:16
    restart: always
    secrets:
      - postgres_master_password
      - postgres_prefilter_password
      - postgres_ingestion_password
      - postgres_connect_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/postgres/init/:/docker-entrypoint-initdb.d/
      - ./db/postgres/postgres.conf:/etc/postgresql/postgresql.conf
    env_file:
      - ./db/postgres/postgres.env
    ports:
      - "31010:5432"
    networks:
      db-network:
        ipv4_address: 192.168.101.2
        aliases: [ "postgres" ]

  mongo:
    image: docker.io/mongo:7
    command: --config /etc/mongod.conf
    restart: always
    secrets:
      - mongo_master_password
      - mongo_ui_password
      - mongo_connect_password
    volumes:
      - mongo-data:/data/db
      - ./db/mongo/init/:/docker-entrypoint-initdb.d/
      - ./db/mongo/mongod.conf.yml:/etc/mongod.conf
    env_file:
      - ./db/mongo/mongo.env
    ports:
      - "31011:27017"
    networks:
      db-network:
        ipv4_address: 192.168.101.3
        aliases: [ "mongo" ]

  adminer:
    build:
      context: ./dockerfiles
      dockerfile: adminer-mongo.Dockerfile
    ports:
      - "31001:8080"
    networks:
      db-network:
        ipv4_address: 192.168.101.10

volumes:
  kafka1-single-log: {}
  postgres-data: {}
  mongo-data: {}
  kafka-connect-offsets: {}

networks:
  kafka-client-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
          ip_range: 192.168.100.128/25
  db-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1
          ip_range: 192.168.101.128/25
  collector-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.102.0/24
          gateway: 192.168.102.1
          ip_range: 192.168.102.128/25
        - subnet: fd10:3456:789a:1::/64

secrets:
  kafka-truststore:
    file: ./secrets/kafka.truststore.jks
  kafka1-keystore:
    file: ./secrets/secrets_kafka1/kafka1.keystore.jks
  client1-keystore:
    file: ./secrets/secrets_client1/client1.keystore.jks
  client2-keystore:
    file: ./secrets/secrets_client2/client2.keystore.jks
  ca-cert:
    file: ./secrets/ca/ca-cert
  client2-cert:
    file: ./secrets/secrets_client2/client2-cert.pem
  client2-key:
    file: ./secrets/secrets_client2/client2-priv-key.pem

  # --- Databases ---
  postgres_master_password:
    file: ./db/postgres/master.secret
  postgres_prefilter_password:
    file: ./db/postgres/prefilter.secret
  postgres_ingestion_password:
    file: ./db/postgres/ingestion.secret
  postgres_connect_password:
    file: ./db/postgres/connect.secret
  mongo_master_password:
    file: ./db/mongo/master.secret
  mongo_ui_password:
    file: ./db/mongo/ui.secret
  mongo_connect_password:
    file: ./db/mongo/connect.secret
