services:
  postgres:
    image: postgres:16
    container_name: postgresdb
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d
      - ./postgresdb_volume:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=domainradar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  prefilter:
    image: prefilter:latest
