[connection]
brokers = ["aiokafka://kafka1:9093"]
use_ssl = true

[connection.ssl]
ca_file = "/run/secrets/ca-cert"
server_verification_required = true
client_cert_file = "/run/secrets/client2-cert"
client_key_file = "/run/secrets/client2-key"
client_key_password = "secret_client2_password"
check_hostname = true

[faust]
producer_compression_type = "zstd"

[rtt]
app_id = "domrad-rtt"
debug = false
ping_count = 5
privileged_mode = false
