[connection]
brokers = ["kafka1:9093"]
use_ssl = true

[connection.ssl]
ca_file = "/run/secrets/ca-cert"
server_verification_required = true
client_cert_file = "/run/secrets/client2-cert"
client_key_file = "/run/secrets/client2-key"
client_key_password = "secret_client2_password"
check_hostname = true

[producer]
"compression.codec" = "zstd"

[mongo]
uri = "mongodb://mongo:27017"
db = "domainradar"
write_batch_size = 100
read_batch_size = 100

[misp]
url = "MISP API URL"
key = "MISP API key"
verify_certificate = true
debug = false
username = "MISP username"
password = "MISP password"

[misp.feeds]
"feed-name-for-CLI" = ["MISP feed ID", "custom category (label)"]
