[connection]
brokers = ["aiokafka://kafka1:9093"]
# brokers = ["aiokafka://kafka1:9093", "aiokafka://kafka2:9094"]
use_ssl = true

[connection.ssl]
ca_file = "/run/secrets/ca-cert"
server_verification_required = true
client_cert_file = "/run/secrets/client2-cert"
client_key_file = "/run/secrets/client2-key"
client_key_password = "secret_client2_password"
check_hostname = true

[rdap_dn]
app_id = "domrad-zone"
debug = false
dns_servers = ["195.113.144.194", "195.113.144.233"]
timeout = 4
rotate_nameservers = false
