version: "3.8"

services:
  kafka1:
    image: apache/kafka:3.7.0
    volumes:
      - kafka1-log:/var/lib/kafka/data
    secrets:
      - kafka-truststore
      - kafka1-keystore
    networks:
      kafka-network:
        ipv4_address: 192.168.45.10
    ports:
      - "9093:9093"
    env_file:
      - ./kafka1.env

  kafka2:
    image: apache/kafka:3.7.0
    volumes:
      - kafka2-log:/var/lib/kafka/data
    secrets:
      - kafka-truststore
      - kafka2-keystore
    networks:
      kafka-network:
        ipv4_address: 192.168.45.20
    ports:
      - "9094:9093"
    env_file:
      - ./kafka2.env

  initializer:
    build:
      context: ..  # The root of the domainradar repo
      dockerfile: ./pipeline-all-in-one/initializer.Dockerfile
    depends_on:
      - kafka1
      - kafka2
    secrets:
      - kafka-truststore
      - client1-keystore
    networks:
      - kafka-network
    volumes:
      - ./initializer.client.properties:/scripts/client.properties
    environment:
      - BOOTSTRAP=kafka1:9093,kafka2:9093
      - COMMAND_CONFIG_FILE=/scripts/client.properties
    entrypoint: /bin/bash

  # collector-zone:
  #   image: domrad-java:latest
  #   build:
  #     context: ./java_pipeline
  #     dockerfile: Dockerfile
  #   command: [ "" ]

volumes:
  kafka1-log:
  kafka2-log:

networks:
  kafka-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.45.0/24
          ip_range: 192.168.45.0/24
  collector-network:
    driver: host
    enable_ipv6: true

secrets:
  kafka-truststore:
    file: ./secrets/kafka.truststore.jks
  kafka1-keystore:
    file: ./secrets/secrets_kafka1/kafka1.keystore.jks
  kafka2-keystore:
    file: ./secrets/secrets_kafka2/kafka2.keystore.jks
  client1-keystore:
    file: ./secrets/secrets_client1/client1.keystore.jks